# Generated by Django 5.2.3 on 2025-06-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturas', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='qrcode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
