# Generated by Django 5.2.3 on 2025-06-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturas', '0004_fatura_texto_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
